Add fixture algorithm change incorrect digest
OCFL/fixtures pull request #67
Opened 2021-04-13 16:11 UTC by pwinckles

Fixture for an object's content digest algorithm changing and one of the digests does not match the content file

2021-04-17 16:33 UTC, zimeon requested changes
In this fixture the `sha512` digests in the `v1` `manifest` for all three files are incorrect. Because the error is in the `manifest` and not the `fixity` block, I think the error code should be `E092` and not `E093`

2021-04-17 16:47 UTC, pwinckles commented
You are right, there is a bug in my logic that decides if a digest mismatch is `E092` or `E093`

2021-04-26 14:24 UTC, pwinckles commented
I changed the error code to `E092`

2021-04-26 17:33 UTC, zimeon approved these changes

2021-05-02 13:29 UTC, awoods approved these changes

2021-05-02 13:30 UTC, merged